### ISSUE TITLE
import not work ;(

### ISSUE THREAD

**Issue by sabinich** [CzBiX/WizNote-to-OneNote#2]
```
vadim@XAIR13:~$ python3 onenote.py
Input WizNote account: v@v
Ignore 1 attachment(s) in "/vav/PDF - major.io"
Ignore 1 attachment(s) in "/vav/AMI Aptio 4.x status codes"
Sign in via:
https://login.live.com/oauth20_authorize.srf?client_id.....&redirect_uri=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf&response_type=code&scope=wl.signin+office.onenote_create
Copy the url of blank page after signed in,
url should starts with "https://login.live.com/oauth20_desktop.srf"
URL: https://login.live.com/oauth20_desktop.srf?code=.....
Notebook to create(such as WizNote):
Create notebook:
Traceback (most recent call last):
  File "onenote.py", line 241, in <module>
    main()
  File "onenote.py", line 229, in main
    notebook_id = create_notebook(session)
  File "onenote.py", line 105, in create_notebook
    resp = session.post(API_BASE + '/notebooks', json={'name': name})
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 497, in post
    return self.request('POST', url, data=data, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by CzBiX** [comment]
Please run `pip3 install -U --user requests` to upgrade `requests` library.

**Comment by sabinich** [comment]
thanks, it works!
