### ISSUE TITLE
and anyway, cannot import: No such file or directory

### ISSUE THREAD

**Issue by sabinich** [CzBiX/WizNote-to-OneNote#4]
```
Notebook to create(such as WizNote): wiznote2                                                                                                        
Create notebook: wiznote2                                                                                                                            
Create section: My Drafts                                                                                                                            
Processing /My Drafts/test (c0b194a8-2dd0-4f31-bd73-2c575e26eb7c)                                                                                    
Traceback (most recent call last):                                                                                                                   
  File "onenote.py", line 241, in <module>                                                                                                           
    main()                                                                                                                                           
  File "onenote.py", line 236, in main                                                                                                               
    upload_doc(session, section_id, data_dir, doc)                                                                                                   
  File "onenote.py", line 205, in upload_doc                                                                                                         
    with ZipFile(doc_path) as zip_file:                                                                                                              
  File "/usr/lib/python3.4/zipfile.py", line 923, in __init__                                                                                        
    self.fp = io.open(file, modeDict[mode])                                                                                                          
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/backup/wiznote/Data/mail@mail/notes/{c0b194a8-2dd0-4f31-bd73-2c575e2
6eb7c}'                                                                                                                                              
```

**Comment by sabinich** [comment]
it my fail. I use WLS and
and  this line 
`return os.path.join(data_path, 'notes', '{%s}' % doc.guid)` was not for my case ;)

**Comment by CzBiX** [comment]
Yes, you can't simply run this script on WLS for WizNote Windows client. It's use different storage structure than Linux client.
In your case, you can remove code about platform detect, and force run code path for Windows.
